### ISSUE TITLE
Heroku demo is down?

### ISSUE THREAD

**Issue by fidian** [sifxtreme/realtime-markdown-viewer#2]
I've been trying to go to https://realtimemarkdown.herokuapp.com/ and get an error message saying that the site owner should check their logs.  Is there another demo site anywhere?

**Comment by sifxtreme** [comment]
I'll be moving this to AWS soon but this demo should work - https://node-markdown.herokuapp.com/

**Comment by fidian** [comment]
In the meantime would you update the README to point to this new URL?

**Comment by sifxtreme** [comment]
For sure!
